source('scripts/descarga_fuentes/descarga_indec_cuenta_generacion_ingreso_vab_insumo_mano_obra.R') # R35C0
source('scripts/descarga_fuentes/descarga_cuentas-nacionales-fund-norte-y-sur.R') # R36C0
source('scripts/descarga_fuentes/descarga_eph_total_urbano_individual.R') # R49C0
source('scripts/descarga_fuentes/descarga_penn_world_tables.R') # R92C0
source('scripts/descarga_fuentes/descarga_cepal_vab_provincial.R') # R221C0
source('scripts/descarga_fuentes/descarga_indec_agregados_macroeconomicos_series_vab_vbp_por_sector.R') # R223C0
source('scripts/descarga_fuentes/descarga_unstats_share_pib_actividad.R') # R224C0
source('scripts/descarga_fuentes/descarga_oecd_tiva_value_added.R') # R225C0
source('scripts/descarga_fuentes/descarga_oecd_tiva_industry_codes.R') # R226C0
source('scripts/descarga_fuentes/schteingart_descriptores_intensidad_tecnologica_tiva.R') # R227C0
source('scripts/descarga_fuentes/descarga_indec_cuenta_generacion_ingreso_series_cgi_sexo_edad.R') # R228C0
source('scripts/descarga_fuentes/descarga_cep_fichas_sectoriales.R') # R229C0
source('scripts/descarga_fuentes/descarga_economic_transformation_database_linked_with_historical_series.R') # R231C0
source('scripts/descarga_fuentes/descarga_oecd_tim_employment.R') # R232C0
source('scripts/descarga_fuentes/descarga_oecd_tim_value_added_per_person_engaged.R') # R233C0
source('scripts/descarga_fuentes/descarga_oecd_tim_clasif_sectores_castellano.R') # R234C0
source('scripts/descarga_fuentes/descarga_boletin_estadisticas_laborales_segun_sexo.R') # R235C0
source('scripts/descarga_fuentes/descarga_cepal_vab_provincial_clasif_sector.R') # R236C0
source('scripts/descarga_fuentes/descarga_MTEySS_OEDE_remuneraciones_empleo_y_empresas.R') # R237C0
source('scripts/descarga_fuentes/descarga_MTEySS_OEDE_remuneraciones_empleo_y_empresas_empleo_registrado.R') # R238C0
source('scripts/descarga_fuentes/descarga_MTEySS_OEDE_remuneraciones_empleo_y_empresas_salarios.R') # R239C0
source('scripts/descarga_fuentes/descarga_CEP_establecimientos_depto_actividad.R') # R240C0
source('scripts/descarga_fuentes/descarga_indec_censo_2022_poblacion_por_depto.R') # R243C0
source('scripts/descarga_fuentes/descarga_indec_censo_2022_redatam_share_hogares_nbi_por_depto.R') # R249C0
source('scripts/limpieza_fuentes/limpieza_cgi_vab_mano_de_obra_indec.R') # R35C5
source('scripts/limpieza_fuentes/limpieza_penn_world_tables.R') # R92C15
source('scripts/limpieza_fuentes/limpieza_eph_total_urbano.R') # R49C16
source('scripts/limpieza_fuentes/limpieza_fundacion_norte_sur_pbi_sectores_millones.R') # R36C82
source('scripts/limpieza_fuentes/limpieza_cepal_vab_provincial.R') # R221C92
source('scripts/limpieza_fuentes/limpieza_indec_VABpb_por_sector_cuadro_3.R') # R223C93
source('scripts/limpieza_fuentes/limpieza_indec_VABpb_por_sector_cuadro_4.R') # R223C94
source('scripts/limpieza_fuentes/limpieza_unstats_ama_share_vab_por_sector_pais.R') # R224C95
source('scripts/limpieza_fuentes/limpieza_oecd_icio_tables.R') # R226C96
source('scripts/limpieza_fuentes/limpieza_oecd_tiva_value_added.R') # R225C97
source('scripts/limpieza_fuentes/limpieza_indec_cuenta_generacion_ingreso_puestos_ar.R') # R228C98
source('scripts/limpieza_fuentes/limpieza_indec_cuenta_generacion_ingreso_puestos_anr.R') # R228C99
source('scripts/limpieza_fuentes/limpieza_indec_cuenta_generacion_ingreso_puestos_na.R') # R228C100
source('scripts/limpieza_fuentes/limpieza_economic_transformation_database_linked_series.R') # R231C102
source('scripts/limpieza_fuentes/limpieza_ocde_tim_employment.R') # R232C103
source('scripts/limpieza_fuentes/limpieza_ocde_tim_value_added_per_person_engaged.R') # R233C104
source('scripts/limpieza_fuentes/limpieza_MTEySS_OEDE_boletin_estadisticas_laboral_segun_sexo_c23.R') # R235C105
source('scripts/limpieza_fuentes/limpieza_cgi_Puestos.R') # R35C106
source('scripts/limpieza_fuentes/limpieza_MTEySS_OEDE_remuneraciones_empleo_y_empresas_empresas_c_5.R') # R237C108
source('scripts/limpieza_fuentes/limpieza_MTEySS_OEDE_remuneraciones_empleo_y_empresas_empresas_c_2.R') # R237C109
source('scripts/limpieza_fuentes/limpieza_MTEySS_OEDE_remuneraciones_empleo_y_empresas_empleo_c_2.R') # R238C110
source('scripts/limpieza_fuentes/limpieza_MTEySS_OEDE_remuneraciones_empleo_y_empresas_salarios_c_2.R') # R239C111
source('scripts/limpieza_fuentes/limpieza_indec_censo_poblacion_por_depto.R') # R243C113
source('scripts/limpieza_fuentes/limpieza_indec_censo_redatam_hogares_con_nbi.R') # R249C118
